problem with pinned slice
How do I set a value in a pinned slice which is holding futures?
When I compile this I get the following error for every case where attempting what was described in the previous statement, is attempted:

```
error[E0308]: mismatched types
   = note: expected type parameter `impl Future<Output = Result<(), LocatchErr>>` (type parameter `impl Future<Output = Result<(), LocatchErr>>`)
              found type parameter `impl Future<Output = Result<(), LocatchErr>>` (type parameter `impl Future<Output = Result<(), LocatchErr>>`)
   = note: a type parameter was expected, but a different one was found; you might be missing a type parameter or trait bound
   = note: for more information, visit https://doc.rust-lang.org/book/ch10-02-traits.html#traits-as-parameters
```

Take note that the mismatched types are both
`impl Future<Output = Result<(), LocatchErr>>`
and
`impl Future<Output = Result<(), LocatchErr>>`

Before you ask, no `LocatchErr` is not defined multiple times.

Also, type casting for `impl` has some restrictions, so I can't do much more than what you see here.

What I'm going to try next is constructing a new slice, to set the entire slice at once.
Sounds terrible, but this doesn't work and that is the only other thing that I can think to try.
I suppose an idea could be to just add all the futures to the slice in init, and then poll a limited number of them during process, so I don't have to deal with this at all.

Yeah that last one sounds good.
I'm still bitter that this doesn't work though.